on:
  push:
    tags:
    - "v[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read
      packages: write

    env:
      COMPOSE_FILES: -f docker-compose.app.yaml -f docker-compose.app.release.yaml
      IMAGE: ghcr.io/concilify/stackage-oauth2-fake

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Build
      run: docker compose ${COMPOSE_FILES} build

    - name: Docker Push
      run: docker push ${IMAGE}:${VERSION}

    - name: Logs
      if: failure()
      run: docker compose ${COMPOSE_FILES} logs
